###
POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}


###
POST http://127.0.0.1:8000/api/signin/
Content-Type: application/json

{
    "username": "testuser",
    "password": "testpassword"
}